#!/bin/bash

source ./colors.sh;

PRODUCTION_SERVER_IP='31.131.17.136'

printCommandsInfo()
{
    echo -e "
 ${CYAN}Server command line interface for the Docker-based web development environment demo.

${YELLOW} Usage:${ENDCOLOR}
    demo <command> [options] [arguments]

${YELLOW} Available commands: ${ENDCOLOR}${GREEN}
    Build and Deploy
    build-production ${BLUE}..................................................................${GREEN} Build production
    push-image ${BLUE}........................................................................${GREEN} Push image
    pull-in-production ${BLUE}................................................................${GREEN} Pull in production
    
    ${ENDCOLOR}
"
}

function buildProduction()
{
    docker build -t idocker2494/esseelitegroup-client ./ -f ./docker/node/Dockerfile --target production
}

function pushImage()
{
    docker push idocker2494/esseelitegroup-client
}

function pullInProduction()
{
    ssh -t root@$PRODUCTION_SERVER_IP 'cd /var/www/esse-elite-group-server && docker image pull idocker2494/esseelitegroup-client'
}

function restartInProduction()
{
    ssh -t root@$PRODUCTION_SERVER_IP 'cd /var/www/esse-elite-group-server && docker compose -f ./docker/docker-compose.production.yml restart client-front-end'
}

case "$1" in
    build-production)
        buildProduction
    ;;
    push-image)
        pushImage
    ;;
    pull-in-production)
        pullInProduction
    ;;
    restart-in-production)
        restartInProduction
    ;;
    *)
        printCommandsInfo
    ;;
esac
