version: '3.9'

services:
  node:
      container_name: ${COMPOSE_PROJECT_NAME}-client
      build: 
          context: ../
          dockerfile: ./docker/node/Dockerfile
          target: ${TARGET}
      ports:
        # - 3000:3000
        - ${DEVELOP_PORT}:8090
        - ${PRODUCTION_PORT}:80